"""Publish: render a runbook into a Markdown docs site (MkDocs-ready)."""
from __future__ import annotations

import os
import subprocess

from jinja2 import Template

from .models import Runbook

PAGE = Template("""# {{ rb.title }}

{{ rb.description }}

## Steps

{% for step in rb.steps %}
### {{ loop.index }}. {{ step.description or step.cmd }}

```bash
{{ step.cmd }}
```
{% endfor %}

---
*Generated by RunbookForge — validated on a clean environment.*
""")

MKDOCS = Template("""site_name: {{ rb.title }}
theme:
  name: material
nav:
  - Runbook: index.md
""")


def publish(rb: Runbook, out_dir: str, build: bool = False) -> str:
    docs = os.path.join(out_dir, "docs")
    os.makedirs(docs, exist_ok=True)
    with open(os.path.join(docs, "index.md"), "w") as fh:
        fh.write(PAGE.render(rb=rb))
    with open(os.path.join(out_dir, "mkdocs.yml"), "w") as fh:
        fh.write(MKDOCS.render(rb=rb))

    if build:
        subprocess.run(["mkdocs", "build"], cwd=out_dir, check=True)
        return os.path.join(out_dir, "site")
    return out_dir
